#!/usr/bin/env python3
"""创建飞书文档并写入结构化内容示例"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))
from feishu_toolkit import FeishuClient

client = FeishuClient()

result = client.create_document_with_content("Auto-generated Report", [
    client.heading_block("Overview", level=1),
    client.text_block("This document was created by Feishu Toolkit."),
    client.heading_block("Data Summary", level=2),
    client.bullet_block("Platform A: 120K plays"),
    client.bullet_block("Platform B: 85K plays"),
    client.bullet_block("Platform C: 200K plays"),
    client.divider_block(),
    client.heading_block("Sample Code", level=2),
    client.code_block(
        "from feishu_toolkit import FeishuClient\n"
        "client = FeishuClient()\n"
        "client.send_text('oc_xxx', 'Hello!')",
        language=49,
    ),
    client.quote_block("Generated by feishu-toolkit"),
])

print("Document created!")
print(f"  ID:  {result['document_id']}")
print(f"  URL: {result['url']}")
